apiVersion: v1
kind: Pod
metadata:
  name: nginx-standalone
  namespace: k8s-day01
  labels:
    app: nginx
    managed-by: manual
spec:
  containers:
    - name: nginx
      image: nginx:stable
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "250m"
          memory: "128Mi"
