apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: k8s-day02
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
