apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: day10
  labels:
    day: "10"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "<REPLACE_WITH_MANAGED_IDENTITY_CLIENT_ID>"
    keyvaultName: "kv-aks-learning"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: api-key
          objectType: secret
          objectVersion: ""
    tenantId: "743c0243-b780-4359-aab6-262117d8871c"
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: db-password
          key: db-password
        - objectName: api-key
          key: api-key
